ccflags-y += -Idrivers/media/platform/msm/camera_v2_scale
ccflags-y += -Idrivers/media/platform/msm/camera_v2_scale/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_scale/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
