ccflags-y += -Idrivers/media/platform/msm/camera_v2_scale
ccflags-y += -Idrivers/media/platform/msm/camera_v2_scale/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_scale/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
